-- MySQL Script generated by MySQL Workbench
-- Wed Aug 23 17:15:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema logistics3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema logistics3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logistics3` DEFAULT CHARACTER SET utf8 ;
USE `logistics3` ;

-- -----------------------------------------------------
-- Table `logistics3`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`user_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `timestamp` VARCHAR(25) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `longitude` DECIMAL(20) NULL,
  `latitude` DECIMAL(20) NULL,
  `population` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`province` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `longitude` DECIMAL(20) NULL,
  `latitude` DECIMAL(20) NULL,
  `population` INT NULL,
  `timestamp` VARCHAR(45) NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`, `region_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_province_region1_idx` (`region_id` ASC),
  CONSTRAINT `fk_province_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `logistics3`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`city_municipal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`city_municipal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `longitude` DECIMAL(20) NULL,
  `latitude` DECIMAL(20) NULL,
  `population` INT NULL,
  `timestamp` VARCHAR(20) NULL,
  `province_id` INT NOT NULL,
  `province_region_id` INT NOT NULL,
  PRIMARY KEY (`id`, `province_id`, `province_region_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_city_municipal_province1_idx` (`province_id` ASC, `province_region_id` ASC),
  CONSTRAINT `fk_city_municipal_province1`
    FOREIGN KEY (`province_id` , `province_region_id`)
    REFERENCES `logistics3`.`province` (`id` , `region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`barangay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`barangay` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `longitude` DECIMAL(20) NULL,
  `latitude` DECIMAL(20) NULL,
  `population` INT NULL,
  `timestamp` VARCHAR(20) NULL,
  `city_municipal_id` INT NOT NULL,
  `city_municipal_province_id` INT NOT NULL,
  `city_municipal_province_region_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_barangay_city_municipal1_idx` (`city_municipal_id` ASC, `city_municipal_province_id` ASC, `city_municipal_province_region_id` ASC),
  CONSTRAINT `fk_barangay_city_municipal1`
    FOREIGN KEY (`city_municipal_id` , `city_municipal_province_id` , `city_municipal_province_region_id`)
    REFERENCES `logistics3`.`city_municipal` (`id` , `province_id` , `province_region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `auth_key` VARCHAR(32) NULL,
  `password_hash` VARCHAR(255) NULL,
  `password_reset_token` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `status` SMALLINT(6) NULL,
  `created_at` VARCHAR(10) NULL,
  `updated_at` VARCHAR(10) NULL,
  `first` VARCHAR(50) NULL,
  `middle` VARCHAR(45) NULL,
  `last` VARCHAR(45) NULL,
  `birthmonth` VARCHAR(45) NULL,
  `birthdate` VARCHAR(45) NULL,
  `birthyear` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NULL,
  `contact_number` VARCHAR(45) NULL,
  `user_type` INT NOT NULL,
  `barangay_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_user_type_idx` (`user_type` ASC),
  INDEX `fk_user_barangay1_idx` (`barangay_id` ASC),
  CONSTRAINT `fk_user_user_type`
    FOREIGN KEY (`user_type`)
    REFERENCES `logistics3`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_barangay1`
    FOREIGN KEY (`barangay_id`)
    REFERENCES `logistics3`.`barangay` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`delivery_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`delivery_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` ENUM('Pending', 'Confirmed', 'In Transit', 'Arrived') NOT NULL,
  `timestamp` VARCHAR(20) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`warehouse_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`warehouse_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `timestamp` VARCHAR(25) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`warehouse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `contact_person_name` VARCHAR(255) NULL,
  `year_established` INT NULL,
  `description` TEXT(100) NULL,
  `area` VARCHAR(45) NULL,
  `timestamp` VARCHAR(25) NULL,
  `open_hours` VARCHAR(15) NULL,
  `close_hours` VARCHAR(15) NULL,
  `open_day` VARCHAR(45) NULL,
  `warehouse_category` INT NOT NULL,
  `barangay_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_warehouse_warehouse_category1_idx` (`warehouse_category` ASC),
  INDEX `fk_warehouse_barangay1_idx` (`barangay_id` ASC),
  CONSTRAINT `fk_warehouse_warehouse_category1`
    FOREIGN KEY (`warehouse_category`)
    REFERENCES `logistics3`.`warehouse_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_warehouse_barangay1`
    FOREIGN KEY (`barangay_id`)
    REFERENCES `logistics3`.`barangay` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`supplier_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`supplier_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `timestamp` VARCHAR(20) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`legal_structure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`legal_structure` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `timestamp` VARCHAR(20) NULL,
  `description` TEXT(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`primary_commodity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`primary_commodity` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `timestamp` VARCHAR(20) NULL,
  `descrption` TEXT(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`supplier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NULL,
  `website` VARCHAR(255) NULL,
  `contact_person` VARCHAR(255) NULL,
  `timestamp` VARCHAR(45) NULL,
  `principal_name` VARCHAR(255) NULL,
  `principal_title` ENUM('CEO', 'President') NULL,
  `business_number_of_year` INT NULL,
  `description` TEXT(100) NULL,
  `supplier_type_id` INT NOT NULL,
  `legal_structure_id` INT NOT NULL,
  `primary_commodity_id` INT UNSIGNED NOT NULL,
  `barangay_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_supplier_supplier_type1_idx` (`supplier_type_id` ASC),
  INDEX `fk_supplier_legal_structure1_idx` (`legal_structure_id` ASC),
  INDEX `fk_supplier_primary_commodity1_idx` (`primary_commodity_id` ASC),
  INDEX `fk_supplier_barangay1_idx` (`barangay_id` ASC),
  CONSTRAINT `fk_supplier_supplier_type1`
    FOREIGN KEY (`supplier_type_id`)
    REFERENCES `logistics3`.`supplier_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_legal_structure1`
    FOREIGN KEY (`legal_structure_id`)
    REFERENCES `logistics3`.`legal_structure` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_primary_commodity1`
    FOREIGN KEY (`primary_commodity_id`)
    REFERENCES `logistics3`.`primary_commodity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_barangay1`
    FOREIGN KEY (`barangay_id`)
    REFERENCES `logistics3`.`barangay` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`supply_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`supply_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `timestamp` VARCHAR(45) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`unit_of_measurement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`unit_of_measurement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`list_of_supply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`list_of_supply` (
  `code` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `date_expiration` VARCHAR(25) NULL,
  `date_received` VARCHAR(25) NULL,
  `description` TEXT(100) NULL,
  `timestamp` VARCHAR(25) NULL,
  `supply_type_id` INT NOT NULL,
  `unit_of_measurement_id` INT NOT NULL,
  `barangay_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `id_UNIQUE` (`code` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_supply_supply_type1_idx` (`supply_type_id` ASC),
  INDEX `fk_supply_unit_of_measurement1_idx` (`unit_of_measurement_id` ASC),
  INDEX `fk_list_of_supply_barangay1_idx` (`barangay_id` ASC),
  CONSTRAINT `fk_supply_supply_type1`
    FOREIGN KEY (`supply_type_id`)
    REFERENCES `logistics3`.`supply_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supply_unit_of_measurement1`
    FOREIGN KEY (`unit_of_measurement_id`)
    REFERENCES `logistics3`.`unit_of_measurement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_list_of_supply_barangay1`
    FOREIGN KEY (`barangay_id`)
    REFERENCES `logistics3`.`barangay` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`supply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`supply` (
  `supplier_id` INT NOT NULL,
  `list_of_supply_code` INT NOT NULL,
  INDEX `fk_supplier_has_list_of_supply_list_of_supply1_idx` (`list_of_supply_code` ASC),
  INDEX `fk_supplier_has_list_of_supply_supplier1_idx` (`supplier_id` ASC),
  PRIMARY KEY (`list_of_supply_code`),
  CONSTRAINT `fk_supplier_has_list_of_supply_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `logistics3`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_has_list_of_supply_list_of_supply1`
    FOREIGN KEY (`list_of_supply_code`)
    REFERENCES `logistics3`.`list_of_supply` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`warehouse_has_supply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`warehouse_has_supply` (
  `warehouse_id` INT NOT NULL,
  `supply_list_of_supply_code` INT NOT NULL,
  PRIMARY KEY (`supply_list_of_supply_code`),
  INDEX `fk_warehouse_has_supply_supply1_idx` (`supply_list_of_supply_code` ASC),
  INDEX `fk_warehouse_has_supply_warehouse1_idx` (`warehouse_id` ASC),
  CONSTRAINT `fk_warehouse_has_supply_warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `logistics3`.`warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_warehouse_has_supply_supply1`
    FOREIGN KEY (`supply_list_of_supply_code`)
    REFERENCES `logistics3`.`supply` (`list_of_supply_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`vehicle_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`vehicle_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `timestamp` VARCHAR(25) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `vehicle_typecol_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`vehicle_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`vehicle_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `timestamp` VARCHAR(45) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`vehicle_size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`vehicle_size` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `timestamp` VARCHAR(25) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`vehicle` (
  `plate_number` VARCHAR(10) NOT NULL,
  `model` VARCHAR(100) NULL,
  `is_lease` TINYINT NULL,
  `timestamp` VARCHAR(25) NULL,
  `available_day` ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday') NULL,
  `available_hour_start` VARCHAR(10) NULL,
  `available_hour_end` VARCHAR(10) NULL,
  `vehicle_type` INT NOT NULL,
  `vehicle_category` INT NOT NULL,
  `owner` INT NOT NULL,
  `vehicle_size` INT NOT NULL,
  `barangay_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`plate_number`),
  UNIQUE INDEX `id_UNIQUE` (`plate_number` ASC),
  INDEX `fk_vehicle_vehicle_type1_idx` (`vehicle_type` ASC),
  INDEX `fk_vehicle_vehicle_category1_idx` (`vehicle_category` ASC),
  INDEX `fk_vehicle_user1_idx` (`owner` ASC),
  INDEX `fk_vehicle_vehicle_size1_idx` (`vehicle_size` ASC),
  INDEX `fk_vehicle_barangay1_idx` (`barangay_id` ASC),
  CONSTRAINT `fk_vehicle_vehicle_type1`
    FOREIGN KEY (`vehicle_type`)
    REFERENCES `logistics3`.`vehicle_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_vehicle_category1`
    FOREIGN KEY (`vehicle_category`)
    REFERENCES `logistics3`.`vehicle_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_user1`
    FOREIGN KEY (`owner`)
    REFERENCES `logistics3`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_vehicle_size1`
    FOREIGN KEY (`vehicle_size`)
    REFERENCES `logistics3`.`vehicle_size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_barangay1`
    FOREIGN KEY (`barangay_id`)
    REFERENCES `logistics3`.`barangay` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`driver` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `middle_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `license_type` ENUM('Class A', 'Class B', 'Class C') NOT NULL,
  `contact_number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`vehicle_has_driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`vehicle_has_driver` (
  `vehicle_plate_number` VARCHAR(10) NOT NULL,
  `driver_id` INT NOT NULL,
  PRIMARY KEY (`vehicle_plate_number`),
  INDEX `fk_vehicle_has_driver_driver1_idx` (`driver_id` ASC),
  INDEX `fk_vehicle_has_driver_vehicle1_idx` (`vehicle_plate_number` ASC),
  CONSTRAINT `fk_vehicle_has_driver_vehicle1`
    FOREIGN KEY (`vehicle_plate_number`)
    REFERENCES `logistics3`.`vehicle` (`plate_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_has_driver_driver1`
    FOREIGN KEY (`driver_id`)
    REFERENCES `logistics3`.`driver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`request` (
  `tracking_number` INT NOT NULL AUTO_INCREMENT,
  `date_requested` VARCHAR(45) NULL,
  `date_needed` VARCHAR(45) NULL,
  `quantity` VARCHAR(45) NULL,
  `description` TEXT(100) NULL,
  `delivery_status` INT NOT NULL,
  `user_id` INT NOT NULL,
  `supply` INT NOT NULL,
  `vehicle_plate_number` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`tracking_number`),
  UNIQUE INDEX `id_UNIQUE` (`tracking_number` ASC),
  INDEX `fk_request_delivery_status1_idx` (`delivery_status` ASC),
  INDEX `fk_request_user1_idx` (`user_id` ASC),
  INDEX `fk_request_warehouse_has_supply1_idx` (`supply` ASC),
  INDEX `fk_request_vehicle_has_driver1_idx` (`vehicle_plate_number` ASC),
  CONSTRAINT `fk_request_delivery_status1`
    FOREIGN KEY (`delivery_status`)
    REFERENCES `logistics3`.`delivery_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `logistics3`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_warehouse_has_supply1`
    FOREIGN KEY (`supply`)
    REFERENCES `logistics3`.`warehouse_has_supply` (`supply_list_of_supply_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_vehicle_has_driver1`
    FOREIGN KEY (`vehicle_plate_number`)
    REFERENCES `logistics3`.`vehicle_has_driver` (`vehicle_plate_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`auth_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`auth_rule` (
  `name` VARCHAR(64) NOT NULL,
  `data` TEXT(255) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`auth_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`auth_item` (
  `name` VARCHAR(64) NOT NULL,
  `type` INT NULL,
  `description` TEXT(255) NULL,
  `data` TEXT(255) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  `auth_rule_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_auth_item_auth_rule1_idx` (`auth_rule_name` ASC),
  CONSTRAINT `fk_auth_item_auth_rule1`
    FOREIGN KEY (`auth_rule_name`)
    REFERENCES `logistics3`.`auth_rule` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`auth_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`auth_assignment` (
  `created_at` INT NULL,
  `user_id` INT NOT NULL,
  `auth_item_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`user_id`, `auth_item_name`),
  INDEX `fk_auth_assignment_auth_item1_idx` (`auth_item_name` ASC),
  CONSTRAINT `fk_auth_assignment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `logistics3`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auth_assignment_auth_item1`
    FOREIGN KEY (`auth_item_name`)
    REFERENCES `logistics3`.`auth_item` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`donation_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`donation_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `timestamp` VARCHAR(45) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`donation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(45) NULL,
  `method` VARCHAR(50) NULL,
  `description` TEXT NULL,
  `donation_type` INT NOT NULL,
  `donor` INT NOT NULL,
  PRIMARY KEY (`id`, `donation_type`, `donor`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_donation_donation_type1_idx` (`donation_type` ASC),
  INDEX `fk_donation_user1_idx` (`donor` ASC),
  CONSTRAINT `fk_donation_donation_type1`
    FOREIGN KEY (`donation_type`)
    REFERENCES `logistics3`.`donation_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_donation_user1`
    FOREIGN KEY (`donor`)
    REFERENCES `logistics3`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`supplier_has_contact_number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`supplier_has_contact_number` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`supplier_has_supply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`supplier_has_supply` (
  `supplier_id` INT NOT NULL,
  `supply_code` INT NOT NULL,
  PRIMARY KEY (`supplier_id`, `supply_code`),
  INDEX `fk_supplier_has_supply_supply1_idx` (`supply_code` ASC),
  INDEX `fk_supplier_has_supply_supplier1_idx` (`supplier_id` ASC),
  CONSTRAINT `fk_supplier_has_supply_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `logistics3`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_has_supply_supply1`
    FOREIGN KEY (`supply_code`)
    REFERENCES `logistics3`.`list_of_supply` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics3`.`auth_item_child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics3`.`auth_item_child` (
  `parent` VARCHAR(64) NOT NULL,
  `child` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`parent`, `child`),
  INDEX `fk_auth_item_has_auth_item_auth_item2_idx` (`child` ASC),
  INDEX `fk_auth_item_has_auth_item_auth_item1_idx` (`parent` ASC),
  CONSTRAINT `fk_auth_item_has_auth_item_auth_item1`
    FOREIGN KEY (`parent`)
    REFERENCES `logistics3`.`auth_item` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auth_item_has_auth_item_auth_item2`
    FOREIGN KEY (`child`)
    REFERENCES `logistics3`.`auth_item` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
